### PR TITLE
Use YAML Block Chomping Indicator to avoid ending line breaks

### LINKED ISSUE #3: Use block-chomping indicator in yaml output
Fixes incorrect line endings when using a dedicated yaml parser.

Reported from https://github.com/NX-Editor/NxEditor.CeadPlugin/issues/1

### PR DESCRIPTION
**Pull request by jordanbtucker**
This PR resolves #3.

### CODE REVIEW

**Review by ArchLeaders — CHANGES_REQUESTED** [review]
Will this break desterilizing because there's an extra character now? (For context, msbt doesn't use a yaml deserializer, but rather just jumps through the characters).

https://github.com/EPD-Libraries/msbt/blob/main/src/msbt.cpp#L58-L83

**Comment by jordanbtucker** [comment]
I does not appear to break deserializing. The code appears to look for the next line that starts with two spaces after the `:` character. It doesn't even handle the `|` character at all.

In other words, the following entries all appear to be equivalent to the code.

```yaml
Item_001: |
  Text_001
Item_001: |-
  Text_001
Item_001: |anything I want here
  Text_001
```

You can even test that with the current version of NxEditor.

Perhaps it would be better if the code searched for `: |\n  ` or `: |-\n  ` to be sure.

Even better if it parsed the text as actual YAML. Although that would add the invalid line breaks back in if the source YAML didn't use the chomping indicator.

**Comment by jordanbtucker** [comment]
As an aside, `MSBT::MSBT(std::string_view text)` doesn't follow YAML correctly since it always strips out the ending line break regardless of a chomping indicator.

**Comment by ArchLeaders** [comment]
> I does not appear to break deserializing. The code appears to look for the next line that starts with two spaces after the `:` character. It doesn't even handle the `|` character at all.
> 
> In other words, the following entries all appear to be equivalent to the code.
> 
> ```yaml
> Item_001: |
>   Text_001
> Item_001: |-
>   Text_001
> Item_001: |anything I want here
>   Text_001
> ```
> 
> Perhaps it would be better if the code searched for `: |\n ` or `: |-\n ` to be sure.
> 
> Even better if it parsed the text as actual YAML. Although that would add the invalid line breaks back in if the source YAML didn't use the chomping indicator.

Ah right, and have you been able to test this or should I?

**Comment by jordanbtucker** [comment]
I tried to test it, but I'm getting the following error when running `./msbt_to_yaml PouchContent.msbt`.

```
terminate called without an active exception
Aborted
```

However, I get that error without my changes too, so there's something wrong with my build pipeline.

**Comment by ArchLeaders** [comment]
Hm, I'll look into it later.

**Pull request merged**
